### PR TITLE
Entry moderation link merge tags

### LINKED ISSUE #1603: Approve an entry with a link sent via an email notification
In GravityView, there’s a concept of [entry approval](https://docs.gravitykit.com/article/88-approving-or-rejecting-entries-in-gravityview). Customers want an easy way to approve an entry from the confirmation email. This ticket is designed to accomplish that.

Check out how Gravity Flow implements this. Use that as a starting point.

- Requires logged-in by _default_, with an option in the merge tag to allow anyone to approve entries (public).
  - Add site-wide GravityView setting to enable `public` modifier, since this is a potential security risk. **Disabled by default.**
  - Add per-form setting to enable `public` modifier. This setting should use the site-wide default by default.
- The link should go to the Gravity Forms "Entries" table for the form by default
  - Add per-form setting to override the redirect URL
- Make link valid for 24 hours by default.
  - Add Merge Tag modifier to adjust timeframe
- Use a nonce
- Store values in options table (not transients), check against time
- Add a salt constant when generating links that can be changed (rotated) if there is a security issue.
- Make sure to verify that the approval request is valid

### Merge Tags

- `{gv_approve_entry}` Link to approve an entry
- `{gv_disapprove_entry}` Link to *dis*approve an entry
- `{gv_unapprove_entry}` Link to *un*approve an entry (reset approval) 

### Modifiers

- `:[\d+d|h|m|s]` Number followed by unit (`d` day, `h` hour, `m` minute, `s` second) of hours the approval link is valid for. `24h` by default.
- `:public` Make the link clickable by anyone, even users who are logged-out. (Requires either site-wide or per-form setting to be enabled).

#### Example usage

  - `{gv_approve_entry}` - Valid for default (24 hours). Private.
  - `{gv_approve_entry:48h}` - Valid for 48 hours. Private.
  - `{gv_approve_entry:20m}` - valid for 10 minutes. Private.
  - `{gv_approve_entry:public}` - Valid for default (24 hours), public
  - `{gv_approve_entry:2h:public}` - valid for 2 hours, public
  - `{gv_approve_entry:20m:public}` - valid for 20 minutes, public

The same modifers will be available for `{gv_disapprove_entry}` and `{gv_unapprove_entry}`.

### PR DESCRIPTION
**Pull request by zackkatz**
Resolves #1603

### CODE REVIEW

**Comment by mrcasual** [comment]
@zackkatz should we use Foundation's [encryption functionality](https://github.com/gravityview/Foundation/blob/main/src/Encryption/Encryption.php) to encrypt/decrypt the token?

**Comment by rafaehlers** [comment]
@zackkatz `:public` links aren't working: https://secure.helpscout.net/conversation/2128403842/46374?folderId=408730

image

**Comment by rafaehlers** [comment]
A user interested in this functionality: https://secure.helpscout.net/conversation/2129159026/46397/

**Comment by zackkatz** [comment]
> @zackkatz `:public` links aren't working: https://secure.helpscout.net/conversation/2128403842/46374?folderId=408730
> 
> image

@rafaehlers I can't find this ticket—the Help Scout link is broken. Do you rememeber whose ticket this was?

**Comment by rafaehlers** [comment]
@zackkatz I've spun up a new instaWP for that here: https://app.instawp.io/wordpress-auto-login?site=$2y$10$g5.iI85NfZoP5pbg5szwbug0F0q8kJb6vYPQPT7y1tE4m.mfbN4Ze

Notification: https://entry-moderation.try.gravitykit.com/wp-admin/?page=gf_edit_forms&view=settings&subview=notification&id=28&nid=63e29bce99624

But you'll need to set up Mailgun for us here: https://entry-moderation.try.gravitykit.com/wp-admin/options-general.php?page=mailgun

**Pull request merged**
