### PR TITLE
Add filter for searchable fields

### PR DESCRIPTION
**Pull request by zackkatz**
@soulseekah Customer doesn't want to use CSS to include fields in search bar, then hide fields using CSS on front-end just to allow searching the fields

- What do you think about adding this filter?
- How about the filter name?
- If you are okay with it, can you write some tests for it and merge it?

Thanks!

### CODE REVIEW

**Comment by zackkatz** [comment]
For me to follow up: https://www.facebook.com/GravityView/inbox/10215237462357424/?notif_id=1574717898137605&notif_t=page_message&mailbox_id=298789240270837&selected_item_id=1459886577

**Comment by soulseekah** [comment]
I don't like the name much. Maybe remove "frontend" and add "allowed" or something.

Will commit the test in a bit. There may be other issues.

**Comment by zackkatz** [comment]
@soulseekah go ahead and rename the filter, please

**Comment by soulseekah** [comment]
> @soulseekah go ahead and rename the filter, please

To what? :) Having a hard time deciding as well. Options:

1. `gravityview/search/searchable_fields/whitelist`
2. `gravityview/search/searchable_fields/allowed`
3. `gravityview/search/searchable_fields`

I somewhat like 1 for now.

**Comment by zackkatz** [comment]
3. Is already taken elsewhere!

Let’s do 1.

**Comment by soulseekah** [comment]
Should be good to merge now. I updated the readme as well.

**Pull request merged**
