### PR TITLE
Admin styles refresh

### PR DESCRIPTION
**Pull request by zackkatz**
- [x] Not all tooltips are JS-enhanced
  - Subtitles for each drop-zone
- [x] [Horizontal radio styles should be on new line](https://i.gravityview.co/8IFBMI+)
- [x] [Link to single entry icon is broken](https://i.gravityview.co/lYkHlq+)
- [x] Duplicated Date Created field  

- [x] Clicking the Link to Entry field doesn't have the click CSS state
- [x] Locks are on all the fields

### CODE REVIEW

**Comment by rafaehlers** [comment]
- [ ] Form Preset images are huge:

image

- [ ] Links are underlined and not properly inlined with text:

image
image

- [ ] Section titles need paddings

image

- [ ] Remove the bottom line behind the tab

image

- [ ] Turn display type buttons inline
- [ ] Buttons not clickable

image

- [ ] Add icons to widgets:

image

- [ ] Newly added widgets don't have config icons:

image

**Comment by zackkatz** [comment]
@rafaehlers It seems the styles were being cached. None of that looks correct, I'm afraid!

**Comment by zackkatz** [comment]
@mrcasual Please help review and fix the (likely) crap JS code I wrote.

**Comment by mrcasual** [comment]
@zackkatz please test to see if there any issues following the merge conflict fix. I'll review the JS afterward.

**Review by mrcasual — APPROVED** [review]

**Comment by mrcasual** [comment]
- [ ] Can't select multi-input fields inside the field picker.

(2.9)


(feature branch)

**Comment by zackkatz** [comment]
- [ ] Merge Tags don't look good for text input fields 

Need to deal with the whole `.gform-settings-input__container--with-append, .gform-settings-input__container--with-merge-tag` issue added in 2.5.

**Pull request merged**
