### PR TITLE
The sequence field

### PR DESCRIPTION
**Pull request by zackkatz**
Implements gravityview/GravityView#984

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1123434173083616)

### CODE REVIEW

**Comment by zackkatz** [comment]
@soulseekah Great work! It's really easy, I love it. 👌

I found one issue: "Reverse the sequence" doesn't work in combination with "First row number"

**Comment by soulseekah** [comment]
> "Reverse the sequence" doesn't work in combination with "First row number"

Oh, I was unsure how to number them with offset. Do we go from that number down to negatives, or do we stop at that number?

First case 10 entries, start at 5: 5, 4, 3, 2, 1, 0, -1, -2, -3, -4
Second case, start at 5: 14, 13, 12, 11, 10, 9, 8, 7, 6, 5

I think second, yes?

**Comment by zackkatz** [comment]
Yep, second.

**Comment by soulseekah** [comment]
Can we merge this into develop?

**Comment by zackkatz** [comment]
I was meaning to test this more last week. Give me one more go at it. I think we’re likely there!

**Pull request merged**
