### PR TITLE
[WIP] Foundation integration

### PR DESCRIPTION
**Pull request by mrcasual**

### CODE REVIEW

**Comment by zackkatz** [comment]
I have GravityView in my plugins folder, **deactivated**. It's not being recognized by Foundation:



When I click install, it fails:

https://i.gravitykit.com/i/fU9SAP+

**Comment by zackkatz** [comment]
- [ ] If using an older version of Maps, settings don't appear anywhere. How should we handle this?

**Comment by mrcasual** [comment]
> * [ ]  I have GravityView in my plugins folder. It's not being recognized by Foundation (when it's deactivated or activated). See below.
> 
> 
> 
> When I click install, it fails:
> 
> https://i.gravitykit.com/i/fU9SAP+

@zackkatz, that's because the text domain changed to `gk-gravityview` and we need to adjust the EDD API response accordingly. It should be `gravityview|gk-gravityview`.

**Comment by zackkatz** [comment]
- [ ] Remove the message about GravityView not having compatible settings

**Comment by zackkatz** [comment]
This is not a new issue (it occurs on `main`), but there's an issue with the Search Widget on a WP Widgets screen.



Going to post a Loom in Slack.

**Comment by zackkatz** [comment]
- [ ] Old settings URL `edit.php?post_type=gravityview&page=gravityview_settings` doesn't redirect to new settings page `admin.php?page=gk_settings`

**Comment by zackkatz** [comment]
Notify this customer: https://secure.helpscout.net/conversation/2070306567/44912?folderId=408730

**Pull request merged**
