### PR TITLE
gv-default-styles.css

### PR DESCRIPTION
**Pull request by juno-w**
clear button leave large after search performed. removing margin will fix so.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995557070797922)

### CODE REVIEW

**Comment by zackkatz** [comment]
@juno0424 Thank you for the pull request! Can you please also modify the search-flexbox.scss and search-legacy.scss files? Those are used to build the gv-default-styles.css file.

**Comment by juno0424** [comment]
Hi Zack, I have modified search-flexbox.scss

**Comment by zackkatz** [comment]
Thanks!

**Comment by zackkatz** [comment]
@juno0424 Please push the updated `search-flexbox.scss` file to GitHub; it is not yet included in this pull request. Thank you.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/689481130/17253/

**Pull request closed without merging**
