### PR TITLE
Speeds up adding fields/widgets in view edit

### PR DESCRIPTION
**Pull request by mrcasual**

### CODE REVIEW

**Comment by mrcasual** [comment]
Outstanding issues:

- [ ] [Switching view type does not update field templates](https://gravityview.slack.com/messages/G727B06MB/convo/G727B06MB-1534370279.000100/)
- [ ] [Lag when opening/closing settings](https://gravityview.slack.com/archives/G727B06MB/p1534371754000100)

**Comment by soulseekah** [comment]
This needs some :love_letter:

**Comment by soulseekah** [comment]
https://secure.helpscout.net/conversation/1034390604/24000?folderId=408730
https://secure.helpscout.net/conversation/1041333314/24147?folderId=408730

**Comment by zackkatz** [comment]
Thanks for the effort, @mrcasual 💯

**Pull request closed without merging**
